"""Builds the downloadable self-assessment PDF from an already-computed tax result.

Uses reportlab (pure-Python, no system library dependency) rather than an HTML->PDF
tool like weasyprint — avoids Pango/Cairo install pain on Windows dev machines and on
Render's free tier.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from modules.tax_computation.engine import TaxComputationResult


def build_report_pdf(
    user_name: str, tax_year: str, result: TaxComputationResult, items: dict | None = None
) -> bytes:
    """`items` is the same {income_items, deduction_items, capital_allowance_items,
    relief_items} shape the web Reports page renders (see
    modules/tax_computation/reporting_helpers.py) — optional so any existing caller
    that doesn't have it yet still gets a valid PDF, just without the itemization.
    """
    items = items or {}
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = [
        Paragraph(f"GigTax Self-Assessment Report — {tax_year}", styles["Title"]),
        Paragraph(f"Prepared for: {user_name}", styles["Normal"]),
        Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]),
        Spacer(1, 0.5 * cm),
    ]

    if result.minimum_wage_exempt:
        story.append(Paragraph(
            "Total income is at or below the National Minimum Wage — fully exempt under "
            "NTA 2025 s.58 / s.162(1)(t). No further computation applies.",
            styles["Normal"],
        ))
    else:
        summary_data = [
            ["Total Income (NTA 2025 s.28)", f"₦{result.total_income:,.2f}"],
            ["Allowable Deductions (ss.20-21)", f"₦{result.total_deductions:,.2f}"],
            ["Capital Allowances (First Schedule)", f"₦{result.total_capital_allowances:,.2f}"],
            ["Statutory Reliefs (s.30)", f"₦{result.total_reliefs:,.2f}"],
            ["Chargeable Income", f"₦{result.chargeable_income:,.2f}"],
            ["Net Tax Payable (Fourth Schedule, s.58)", f"₦{result.net_tax:,.2f}"],
        ]
        summary_table = Table(summary_data, colWidths=[9 * cm, 6 * cm])
        summary_table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.5 * cm))

        item_sections = [
            ("Income", items.get("income_items", [])),
            ("Allowable Deductions", items.get("deduction_items", [])),
            ("Capital Allowances", items.get("capital_allowance_items", [])),
            ("Statutory Reliefs", items.get("relief_items", [])),
        ]
        if any(entries for _, entries in item_sections):
            story.append(Paragraph("Itemized Breakdown", styles["Heading2"]))
            for section_label, entries in item_sections:
                if not entries:
                    continue
                story.append(Paragraph(section_label, styles["Heading3"]))
                item_data = [["Category", "Amount"]] + [
                    [entry["category_name"], f"₦{entry['amount']:,.2f}"] for entry in entries
                ]
                item_table = Table(item_data, colWidths=[9 * cm, 6 * cm])
                item_table.setStyle(TableStyle([
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                ]))
                story.append(item_table)
                story.append(Spacer(1, 0.3 * cm))

        story.append(Paragraph("Band-by-band computation (Fourth Schedule)", styles["Heading2"]))
        band_data = [["Rate", "Amount in Band", "Tax"]]
        for band in result.band_breakdown:
            band_data.append([f"{band.rate * 100:.0f}%", f"₦{band.amount_in_band:,.2f}", f"₦{band.tax:,.2f}"])
        band_table = Table(band_data, colWidths=[3 * cm, 6 * cm, 6 * cm])
        band_table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
        ]))
        story.append(band_table)

    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(
        "This is a self-assessment estimate generated by GigTax based on the transactions you "
        "reviewed and approved. It is not a substitute for professional tax advice.",
        styles["Italic"],
    ))

    doc.build(story)
    return buffer.getvalue()
