"""add itemized breakdown to tax computations

Revision ID: 08f32bba4e44
Revises: 3aec08ba1b45
Create Date: 2026-09-10 20:27:53.200970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f32bba4e44'
down_revision: Union[str, Sequence[str], None] = '3aec08ba1b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_computations', sa.Column('items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_computations', 'items')
    # ### end Alembic commands ###
