"""add session_id to advisory_queries for chat memory

Revision ID: 323a66e21f6f
Revises: 414a02b21ea9
Create Date: 2026-09-10 10:59:04.220365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '323a66e21f6f'
down_revision: Union[str, Sequence[str], None] = '414a02b21ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable first — existing rows (pre-dating the session_id concept) each get
    # their own random session, then the column is locked down to NOT NULL. A plain
    # `nullable=False` add would fail outright against any existing row.
    op.add_column('advisory_queries', sa.Column('session_id', sa.UUID(), nullable=True))
    op.execute("UPDATE advisory_queries SET session_id = gen_random_uuid() WHERE session_id IS NULL")
    op.alter_column('advisory_queries', 'session_id', nullable=False)
    op.create_index(op.f('ix_advisory_queries_session_id'), 'advisory_queries', ['session_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisory_queries_session_id'), table_name='advisory_queries')
    op.drop_column('advisory_queries', 'session_id')
    # ### end Alembic commands ###
