"""add annual_rent_paid to users

Revision ID: 3aec08ba1b45
Revises: 968f4411dafc
Create Date: 2026-09-10 20:05:46.657026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aec08ba1b45'
down_revision: Union[str, Sequence[str], None] = '968f4411dafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('annual_rent_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'annual_rent_paid')
    # ### end Alembic commands ###
