"""add server default to tax_computations.last_updated

Revision ID: 69510f68ed5e
Revises: dc0d5fcdad7d
Create Date: 2026-09-10 09:28:05.529931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69510f68ed5e'
down_revision: Union[str, Sequence[str], None] = 'dc0d5fcdad7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
