"""add capital asset handling

Revision ID: a8eb50becc79
Revises: 69510f68ed5e
Create Date: 2026-09-10 09:50:50.883661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8eb50becc79'
down_revision: Union[str, Sequence[str], None] = '69510f68ed5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('disposed', sa.Boolean(), nullable=True),
    sa.Column('disposed_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.add_column('categories', sa.Column('asset_class', sa.String(length=20), nullable=True))
    op.add_column('tax_computations', sa.Column('total_capital_allowances', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_computations', 'total_capital_allowances')
    op.drop_column('categories', 'asset_class')
    op.drop_table('assets')
    # ### end Alembic commands ###
