"""initial schema

Revision ID: dc0d5fcdad7d
Revises: 
Create Date: 2026-09-10 09:01:56.050788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0d5fcdad7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('developer_slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tax_treatment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('developer_slug')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('occupation_type', sa.String(length=50), nullable=True),
    sa.Column('state_residence', sa.String(length=50), nullable=True),
    sa.Column('tax_year', sa.String(length=4), nullable=True),
    sa.Column('has_home_office', sa.Boolean(), nullable=True),
    sa.Column('home_office_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('google_drive_connected', sa.Boolean(), nullable=True),
    sa.Column('google_refresh_token_encrypted', sa.String(length=500), nullable=True),
    sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('advisory_queries',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(length=1000), nullable=False),
    sa.Column('response_text', sa.String(length=5000), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('retrieved_sources', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_table('custom_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword_pattern', sa.String(length=255), nullable=False),
    sa.Column('assigned_category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('statement_uploads',
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'LOCKED', name='parsingstatus'), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('statement_id')
    )
    op.create_table('tax_computations',
    sa.Column('computation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.String(length=4), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('total_reliefs', sa.Float(), nullable=True),
    sa.Column('taxable_income', sa.Float(), nullable=True),
    sa.Column('estimated_tax_owed', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('computation_id')
    )
    op.create_table('tax_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('computation_id', sa.UUID(), nullable=False),
    sa.Column('generation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['computation_id'], ['tax_computations.computation_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('computation_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('ai_category_id', sa.UUID(), nullable=True),
    sa.Column('user_category_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('tax_treatment', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('income_source', sa.String(length=255), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('deductibility_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ai_category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statement_uploads.statement_id'], ),
    sa.ForeignKeyConstraint(['user_category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('receipts',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('transactions')
    op.drop_table('tax_reports')
    op.drop_table('tax_computations')
    op.drop_table('statement_uploads')
    op.drop_table('custom_rules')
    op.drop_table('advisory_queries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
