"""add error_message to statement_uploads

Revision ID: ec07c7fb03d6
Revises: 08f32bba4e44
Create Date: 2026-09-11 00:00:47.356126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec07c7fb03d6'
down_revision: Union[str, Sequence[str], None] = '08f32bba4e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement_uploads', sa.Column('error_message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statement_uploads', 'error_message')
    # ### end Alembic commands ###
